// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Eql2gB81gQc_jZvT8EPRmhPhK-fjm2U',
    appId: '1:307474437789:web:6ec75749a2d3f1f83ca674',
    messagingSenderId: '307474437789',
    projectId: 'e-commerce1a',
    authDomain: 'e-commerce1a.firebaseapp.com',
    storageBucket: 'e-commerce1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJsDUs1JoWKIn6PojOOT3VRFO9vuevAk',
    appId: '1:307474437789:android:526980952da32bc53ca674',
    messagingSenderId: '307474437789',
    projectId: 'e-commerce1a',
    storageBucket: 'e-commerce1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrTDtuA1tZ8rx9AQImMwwlHVj9PckkRhQ',
    appId: '1:307474437789:ios:822b185a64c51e163ca674',
    messagingSenderId: '307474437789',
    projectId: 'e-commerce1a',
    storageBucket: 'e-commerce1a.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
